FROM node:16.20.2-buster AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm install

COPY . .

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.25.2

COPY --link nginx.conf /etc/nginx/conf.d/default.conf

COPY --link --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 8080