services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # target: dev
    init: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CI=true
    restart: unless-stopped
    networks:
      - frontend
  
  client-react-nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile-nginx
    init: true
    ports:
      - "80:8080"
    restart: unless-stopped
    networks:
      - frontend


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    init: true
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://db/vidly
    restart: unless-stopped
    networks:
      - frontend
      - backend

  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - vidly:/data/db
    networks:
      - backend 

volumes:
  vidly:
networks:
  frontend:
  backend: