apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: vidly-user
      db: fullstack-app
      passwordSecretRef:
        name: mongodb-credentials
      roles:
        - db: fullstack-app
          name: readWrite
      scramCredentialsSecretName: mongo-credentials # the name of the secret that will be created to store the user's SCRAM credentials
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

